# Site settings
title: Culaccino
SEOTitle: 冰界的博客 | Culaccino Blog
header-img: img/upd_img5.png
email: culaccino_9350@163.com
description: "Study to reduce prejudice."
keyword: "Culaccino,Computer Vision,ACM-XCPC,Machine Learning"
url: "http://BBBoundary.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/BBBoundary/BBBoundary.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "People have Dreams."
sidebar-avatar: /img/upd_img1.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     5621847260
zhihu_username:     bing-jie-11
github_username:    BBBoundary
#facebook_username:  baiying.qiu.7
#jianshu_username:   cdba90a00cb3
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



#评论系统
#Disqus settings（https://disqus.com/）
disqus_username: Culaccino

# Gitalk
#gitalk:
enable: true    #是否开启Gitalk评论
clientID: a6d616f2f2494f619256                            #生成的clientID
clientSecret: 6e7c8e116ac88e55734797aeabbc3bc2e6516419    #生成的clientSecret
repo: BBBoundary.github.io    #仓库名称
owner: BBBoundary    #github用户名
admin: BBBoundary
distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics3
ga_track_id: 'UA-159837212-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Gghost",
        href: "https://gjnghost.top"
    },{
        title: "Wenzhuan",
        href: "https://wzyxv1n.top"
    },{
        title: "K0ule",
        href: "https://k0u1e.github.io"
    },{
        title: "Edwiv",
        href: "https://edwiv.com"
    },{
        title: "louyu",
        href: "https://louyu.site"
    },{
        title: "Garvey",
        href: "https://ggggarvey.github.io"
    }
]
